services:

  apigateway:
    container_name: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:5000"

  authservice:
    container_name: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5001:5001"

  packageservice:
    container_name: packageservice
    build:
      context: .
      dockerfile: PackageService/Dockerfile
    ports:
      - "5002:5002"

  routeservice:
    container_name: routeservice
    build:
      context: .
      dockerfile: RouteService/Dockerfile
    ports:
      - "5003:5003"
