version: '3.9'

services:

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000"

  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5001:80"

  packageservice:
    build:
      context: .
      dockerfile: PackageService/Dockerfile
    ports:
      - "5002"

  routeservice:
    build:
      context: .
      dockerfile: RouteService/Dockerfile
    ports:
      - "5003"
