version: '3.9'

services:

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:8080"

  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5001:8080"

  packageservice:
    build:
      context: .
      dockerfile: PackageService/Dockerfile
    ports:
      - "5002:8080"

  routeservice:
    build:
      context: .
      dockerfile: RouteService/Dockerfile
    ports:
      - "5003:8080"
